-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Laitos CASCADE;
DROP TABLE IF EXISTS Oppilas CASCADE;
DROP TABLE IF EXISTS Opettaja CASCADE;
DROP TABLE IF EXISTS Vastuuhenkilö CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Ilmoittautuminen CASCADE;
DROP TABLE IF EXISTS Kysely CASCADE;
DROP TABLE IF EXISTS Kysymys CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
